### ISSUE TITLE
voice protocol updates

### ISSUE THREAD

**Issue by satra** [ReproNim/reproschema#114]
@sanuann  - updates needed for voice protocol: 
- [x] 1. demographics should only ask for sex and handedness
- [ ] 2. the displayed content for the study should be updated
- [ ] 3. An approximate consent should be created (this will be updated after review by IRB)
- [x] 4. Screening should be connected to remote server
- [x] 5. data collection should be tested on remote server (requires zip export)
- [x] 6. skip needs to be disabled for screening
- [x] 7. NDA gender question should be renamed Sex
- [x] 8. For this protocol we only need year of birth
- [x] 9. Make the stop marker on the map the media lab (how well can the map be seen on a phone? if not switch to a different type of map. it does not have to be a google map)
- [x] 10. For the voice tasks make sure the description says the following:
```
For each task, you should hit the record button before speaking and then 
stop once you are done speaking. You may hit play to hear what was recorded.
```
- [x] 11. There is no passage in the multipart widget
- [x] 12. The multipart widget is not functional (redo-recording in the end does not go back to the first screen)
- [x] 13. The thank you should be a separate screen.

**Comment by sanuann** [comment]
is point 8 also required along with the demographics info (point 1)?

**Comment by satra** [comment]
actually for this protocol we may need all of these:

Age; Race/Ethnicity; Gender; State; Country of Birth; Native Speaker/Accent; Diagnosed with any mental-health disorder; Any health condition; Medication usage

**Comment by akeshavan** [comment]
for 4. do you mean that the remote server needs to be created/deployed?

**Comment by satra** [comment]
i'll take care of 4.

**Comment by sanuann** [comment]
what should go in for point 2?

**Comment by satra** [comment]
> what should go in for point 2?

the front page should be updated to reflect what you want the person to do. i.e. instructions.

**Comment by satra** [comment]
remote server check will return a token with an expiry time:

```
$ curl --header "Content-Type: application/json" --request POST --data '{"total_score":25}'  https://sig.mit.edu/vb/check/

{"qualified":"yes","token":"fd644544-b6dc-4b25-b206-475c2c2d20c2","expiry":1555027152}
```

the user has to finish the assessment within the expiry time and submit 

```
$ curl --header "Content-Type: application/json" --request POST --data '{"token":"fd644544-b6dc-4b25-b206-475c2c2d20c2"}'  https://sig.mit.edu/vb/submit/
{"status":"accepted"}
```

token becomes invalid either after expiry time or if it has been submitted.

```
$ curl --header "Content-Type: application/json" --request POST --data '{"token":"fd644544-b6dc-4b25-b206-475c2c2d20c2"}'  https://sig.mit.edu/vb/submit/
Token not valid
```

for the moment you can reset state simply by doing a GET on 

```
$ curl https://sig.mit.edu/vb/reset/
{"0":0,"1":0,"2":0,"3":0,"4":0}
```

but you can also reset internal params by doing:

```
$ curl --header "Content-Type: application/json" --request POST --data '{"max_per_bin": 1, "slop_factor": 1, "expiry_mins": 20}'  https://sig.mit.edu/vb/reset/
{"status":"reset-post"}
```
these will obviously be disabled in production instance.

more details of server at: https://github.com/sensein/voice-backend/blob/master/serve.py

let me know if you have questions. also we would need to test it with submitting actual data.

**Comment by satra** [comment]
i'm going to close this as most issues have been addressed and we are now restarting protocols with a slightly different framework.
