### ISSUE TITLE
items moved to root level for reusability

### ISSUE THREAD

**Issue by zaliqarosli** [ReproNim/reproschema#118]

**Comment by satra** [comment]
this was discussed and resolved by keeping items within activities.

**Comment by zaliqarosli** [comment]
hi @satra , how have you resolved the reusability of the items while keeping them within activities?

**Comment by satra** [comment]
by direct pointers to the URLs of items. an example of reuse of elements is in this example repo:  https://github.com/sensein/covid19/

what we still need are:
- a search operation
- versioning (though technically this can be achieved by pointing to git commitish urls instead of master)
