### ISSUE TITLE
Names for schema, library, schema-ui

### ISSUE THREAD

**Issue by satra** [ReproNim/reproschema#138]
we need to decide on a few names for things:

- [ ] the schema standard for assessments
- [ ] the library of assessments and 
- [ ] library of applets/studies
- [ ] module for ui to interact with applets/studies

many components of this is joint work with our partners at CMI and McGill. so if they are not on this, please ping them as well.

**Comment by akeshavan** [comment]
@zaliqarosli @shnizzedy

**Comment by shnizzedy** [comment]
:100:

Regarding 
> - [ ] the library of assessments and applets/studies (currently being served by github)

is the idea for ONLY ONE such library to exist, or is the question what to name this particular such library?

**Comment by satra** [comment]
in the ideal world we would want scientists to contribute to one library, but the schema and it's instantiation as jsonld does not preclude the URL to be anywhere specific. i would also separate out library of activities from library of studies/applets

i definitely would like a common library of activities (mostly standardized and reusable things) and a separate common library of studies/applets (mostly custom things, some reusable).

so we need two names for those two things.

**Comment by satra** [comment]
following up on this, we will soon be changing 
1. name of this repo to reprolib
2. name of activity-sets to protocols

**Comment by satra** [comment]
this has now been completed.
