### ISSUE TITLE
"downstream" schemas break when changes are made in this repo

### ISSUE THREAD

**Issue by Remi-Gau** [ReproNim/reproschema#274]
I just realized that the [COBIDAS app](https://cobidas-checklist.herokuapp.com/#/) does not "work" anymore eventhough I have not changed anything.

By having a look around it seems that some changes were made in the ReproNim/schema-standardization that the COBIDAS schema points to. I have tried to see how to fix that and I am sure that with enough I can get it to work but I am also thinking of ways to make that fixing faster in the future.

For that, would it make sense to create a "dummy" schema that contains "activity set + activity + items"?

From a pedagogical point of view, this could be used to show with very simple json files how create a schema and the different type of items allowed. But if this dummy schema is kept up to date, this could help "troubleshoot" when downstream schemas break by being able to quickly identify which field has been modified.

What do you say?

PS: I have not taken the time to read how to validate the schemas using the tools on the repronim schema builder [repo](https://github.com/ReproNim/reproschema-builder/blob/master/validation/ActivitySetShape.ttl) so feel free to tell me to go RTFM as this might simply solve my problem.

**Comment by shnizzedy** [comment]
Related: #3, #52, #138, #174

**Comment by sanuann** [comment]
@Remi-Gau 
The major changes which I made was to :

- remove the `.jsonld` extension from all files
- rename the activity/activity-sets directories and/or files
- use prefix `reproschema` to point to `https://raw.githubusercontent.com/ReproNim/schema-standardization/master/schemas/`. 

This change was pushed to the master branch. it should not have affected your app (as I see it points to a different branch `neurovault`)

I'll fix the schema-ui ASAP. think its a problem with `jsonld` file extensions.

the idea of a dummy schema is great. It will sure speed troubleshooting!

**Comment by satra** [comment]
i think we should do more of the breaking changes immediately so that we can get back to a more stable state. (repo renaming to `reprolib` and activity-set to protocol) and then update the schema-ui reproterms. i also what to change schema-ui to `reproschemaui`.

and after this we should fix the remaining issues with validation (e.g., scoring_logic) and release a stable schema so that we can start depending on it.

**Comment by Remi-Gau** [comment]
Thanks @sanuann for the list of changes. This will definitely help fix things.

@satra I guess I will wait till all the "breaking is done" before I start working on a dummy schema. :-)

Most likely I will also wait for those to be done before I really start fixing the things on the COBIDAS front.

**Comment by satra** [comment]
@Remi-Gau @shnizzedy @zaliqarosli - we are done with most of the breaking changes

we now have a service: https://schema.repronim.org/rl/
and a ui service: https://schema.repronim.org/ui/

- the schema service is like schema.org + a library of assessments and protocols (our intent is to maintain the library here and to provide any necessary abstractions on the API to make it easier for developers to use these activities/protocols. e.g., flattened graphs, etc.,.

- the ui service is meant for viewing, wouldn't really be used for data collection, although one potentially could do personal collections using the export button

we have to answer a few question/do a few more things:

1. is the service the permanent URLs, i.e. just like schema.org, we expect the terms to be delivered from `schema.repronim.org/rl/terms/...` and `schema.repronim.org/rl/schemas/...`

 (the github repo is still where changes take place, just like schema.org data)

2. how we encode scoring and branching logic. we need to make some changes to make this conformant with jsonld. it was a hackjob earlier.

3. we need to come to a decision on versioning. the current deployment is version less.

4. refactor reproschema-ui, so people can redeploy/use it without having to upload activities or protocols to the reproschema repo. currently this ui assumes things are in the reproschema repo

5. in addition to all these updates @sanuann was working on validation. as soon as she gives a thumbs up, we will run through the repo with the validator identifying issues and fixing them. after that we should be able to release the current schema as stable version.

please post any thoughts/concerns etc.,. we do want to move this towards a stable resource.

**Comment by Remi-Gau** [comment]
Finally had some time to work on this during the weekend.

>     1. is the service the permanent URLs, i.e. just like schema.org, we expect the terms to be delivered from `schema.repronim.org/rl/terms/...` and `schema.repronim.org/rl/schemas/...`
What would be the alternative?


>     3. we need to come to a decision on versioning. the current deployment is version less.
YES. Definitely needed. Did you have any idea in mind on how to go about this? I have only worked with zenodo so far but I doubt this is appropriate for what we want.


>     4. refactor reproschema-ui, so people can redeploy/use it without having to upload activities or protocols to the reproschema repo. currently this ui assumes things are in the reproschema repo
Currently I am pointing my app on my fork of the repo but this is not optimal I would say. So I am all ears about suggestions anyone might have.


>     5. in addition to all these updates @sanuann was working on validation. as soon as she gives a thumbs up, we will run through the repo with the validator identifying issues and fixing them. after that we should be able to release the current schema as stable version.
I started working on an activity set / activity / items that could be used as a "starter kit" to show how to use the schema. Hopefully I can complete it soon enough.
