### ISSUE TITLE
Adapting for mobile cellphone use

### ISSUE THREAD

**Issue by danielmlow** [ReproNim/reproschema#310]
On my cellphone (old iphone 5s), the language and index are to the side, and this makes the activities be crammed up and narrower than they should be:
![image](https://user-images.githubusercontent.com/14787791/74968596-0b486280-53e9-11ea-969b-5d19aa5fcdce.png)

So perhaps we can place the language and index on top so it's all one column? Also the font could be a little smaller?

**Comment by sanuann** [comment]
pls post this issue on the voice-study repo.
