### ISSUE TITLE
improve naming of scoringLogic and Scoring

### ISSUE THREAD

**Issue by satra** [ReproNim/reproschema#405]
`scoringLogic` is a subset of all computations that could be performed and not all computations will be scoring. For example, one may want to do conversion from one unit to another.

proposal:
`scoringLogic` to `compute` 
`Scoring` to `ComputeSpecification`

@Remi-Gau and @sanuann - i'm not set on the words here and would appreciate some input.

**Comment by Remi-Gau** [comment]
Hmmm...

Trying to see this from the "new user perspective" and making sure those names are transparent enough. 

`compute` and `ComputeSpecification` seem good enough to me. 

If my sleep deprived brain manages to get some better idea I will get back to you. :smile:

**Comment by satra** [comment]
@sanuann - could you please make the changes and update all the places where these are used?

**Comment by sanuann** [comment]
`compute` and `ComputeSpecification` looks good to me too. Will update.

**Comment by satra** [comment]
closed via #411
