### ISSUE TITLE
add a consent form section to an activity set

### ISSUE THREAD

**Issue by akeshavan** [ReproNim/reproschema#41]
at the activity-set level, we should have a key that links to the text of a consent form

**Comment by sanuann** [comment]
do you mean similar to the preamble in the activity level?

**Comment by akeshavan** [comment]
no, we will only display it once to the user, maybe as a popup or something. Right now we are taking UI components from this repository and adding in Mindlogger authentication so we can save data (https://mindlogger-web.anisha.pizza && https://github.com/ChildMindInstitute/mindlogger-web)

**Comment by akeshavan** [comment]
@satra - do you have the consent form for this pilot, or should we make something like this: https://www.dropbox.com/s/kpfwcavscg32fj7/VoiceUp_wiresFrames_StoryBoardUpdated_040716.pdf?dl=0 ? Are we already through the IRB process?

**Comment by satra** [comment]
@sanuann - i think this is now done, right?
