### ISSUE TITLE
isVisShape uses an undefined term

### ISSUE THREAD

**Issue by satra** [ReproNim/reproschema#412]
https://github.com/ReproNim/reproschema/blob/refactor-1.0/validation/reproschema-shacl.ttl#L217

should the target of isVis also be a jsExpression?

**Comment by sanuann** [comment]
the above link returns a 404 now. Perhaps this is fixed now?

**Comment by satra** [comment]
this was still under refactor which has been deleted. i should really be pasting committish links.
