### ISSUE TITLE
document upload item ?

### ISSUE THREAD

**Issue by Remi-Gau** [ReproNim/reproschema#440]
Quick question: there is a DocumentUpload widget in the reproschema-ui but I am not sure how if it exists in the schema.

Am I missing something?

**Comment by sanuann** [comment]
yes, that widget exists. but not sure if it is updated to work with the latest reproschema format. I will check and let you know

**Comment by Remi-Gau** [comment]
thanks :smile_cat:

**Comment by yibeichan** [comment]
@Remi-Gau sorry for this 3-year-late reply, but were you looking for https://github.com/ReproNim/demo-protocol/blob/master/activities/Activity1/items/document_upload_item?

**Comment by Remi-Gau** [comment]
Nice thanks
