### ISSUE TITLE
Bad link in "Project Structure" documentation

### ISSUE THREAD

**Issue by dnkennedy** [ReproNim/reproschema#446]
In the Project Structure section (https://www.repronim.org/reproschema/20_project_structure/) of the documentation, in the "Reproschema-library" section, there is a sentence that says: "All assessments are listed in the activity folder and are served **here** if you want to visualize them." The link of "here" leads to(https://schema.repronim.org/rl/) and an error: "502 Bad Gateway / nginx/1.14.0 (Ubuntu)"

**Comment by dnkennedy** [comment]
Also in that same doc, the same bad url appears at the section "Reprolib-server" :
"This contains some additional information on how the activities are served on https://schema.repronim.org/rl/."

https://schema.repronim.org/rl/ seems to be bad...

**Comment by satra** [comment]
yes, we need to revive that service. i'll take a look perhaps today.

**Comment by Remi-Gau** [comment]
probably worth adding a link checker

**Comment by Remi-Gau** [comment]
Link checker is in place and does.not seem to complain about this so I will close it.

Reopen if this is still an issue.
