### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by Remi-Gau** [ReproNim/reproschema#448]
Need to reference reproschema in a paper I am working on.
I don't think we have any ways to cite this at the moment except linking to the repo.

Suggestion: add a CITATION.CFF file, link the repo to zenodo and make a release the repo to get a zenodo DOI.

Obviously happy to hear and help implement other suggestions.

**Comment by satra** [comment]
there is one here: https://zenodo.org/record/4626132 (which refers to the latest schema release).

**Comment by Remi-Gau** [comment]
The first line of the read me and I manage to miss it. 

I think I need more holidays.
