### ISSUE TITLE
Unable to parse jsonld due to context path

### ISSUE THREAD

**Issue by cmungall** [ReproNim/reproschema#450]
I'm trying to assemble the whole schema as a single ttl file. I am trying to use jena to do this one file at a time without success:

```
riot --syntax=jsonld  reproschema/terms/Activity
08:57:41 ERROR riot            :: invalid term definition: 1.1
```

also with robot:

```
robot convert  -i terms/Activity -o Activity.ttl
Not a valid (absolute) URI: @context
```

I believe this is caused by the relative context path

also when attempting from the web:

```
robot convert  -I  http://schema.repronim.org/Activity -o Activity.ttl
org.semanticweb.owlapi.io.OWLOntologyCreationIOException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
```

**Comment by satra** [comment]
if you install reproschema-py it will do this automatically for you. 

```bash
pip install reproschema
reproschema convert --format turtle https://raw.githubusercontent.com/ReproNim/reproschema/master/terms/Activity
```

we are relying on github services to provide relative link resolution. and if you were to clone the repo locally, the reproschema library spins up a local server to provide resolution.

**Comment by Remi-Gau** [comment]
Will assume that the thumbs up on that late post means this solved the issue.

Reopen if that's not the case.
