### ISSUE TITLE
encoding frequency of assessments

### ISSUE THREAD

**Issue by akeshavan** [ReproNim/reproschema#46]
we should encode whether or not an activity can only be completed once or can be completed multiple times.

If it can be completed multiple times:
- how many times in total?
- is there a minimum time-period a user must wait to take it again?
- is there an N times per day/week/month sort of thing

**Comment by shnizzedy** [comment]
We're already using [XML Schema Definition Language (XSD)](https://www.w3.org/TR/xmlschema11-2/), which should allow us to encode these kinds of constraints. @akeshavan do you have an example of an activity with these kinds of restraints in mind?

**Comment by akeshavan** [comment]
For @satra 's voice pilot, we only need a single timepoint

But let's take the HBN sleep behavior as an example: we only need it 1x/day but the exact time doesn't matter. Perhaps we should schedule a call with cameron's group to see what kind of examples they have

**Comment by satra** [comment]
for the pilot, yes. but not in general. in fact we would really like to turn this into a self-annotation app at some point in the not too distant future. in this futuristic world,

a person will press a button to indicate some state, and that will trigger a set of data collection of some kind. it may trigger a one time collection, a daily collection, etc.,. so in general there needs to be a specification of time that is associated with an activity.

in the past we used a cron format specification alongside each activity in an activity set. i think that is the best place for it. 

and one constraint we put on it was:
-  if the user does not do it at this time, the user gets a reminder at some interval over some duration, up to the next presentation of that activity/item.

we may have to discuss a more complicated case, where items are randomly selected and randomly presented over some time interval. there is nothing in the schema that allows this information.

also regarding constraints do take a look at SHACL (my world of linked things).

**Comment by akeshavan** [comment]
> in the past we used a cron format specification alongside each activity in an activity set. i think that is the best place for it.

If we go with cron, we could implement with: https://www.npmjs.com/package/node-schedule or https://github.com/kelektiv/node-cron which would be pretty convenient..

> if the user does not do it at this time, the user gets a reminder at some interval over some duration, up to the next presentation of that activity/item

Perhaps a `frequency` cron-like spec and a `reminderInterval` spec

> we may have to discuss a more complicated case, where items are randomly selected and randomly presented over some time interval. there is nothing in the schema that allows this information.

I want a real-life, compelling use case for this. I don't want to add complexity for a fringe use-case!

**Comment by satra** [comment]
> I want a real-life, compelling use case for this. I don't want to add complexity for a fringe use-case!

see the HBN-SSI assessments for voice (i know i wrote them, so you may still consider it a fringe use-case).

but in general for almost any daily recording, one would likely want to sample different items. the random presentation times was something that's in mindlogger presently.

however, you don't have to implement that right away, just keep it in mind. i want to first make sure all cross-sectional things work. then we can do longitudinal pieces.

**Comment by shnizzedy** [comment]
Reading through these examples, I think maybe this issue and https://github.com/ChildMindInstitute/mindlogger-app/issues/25 could be generalized into assessment access constraints, which could be frequency-of-assessment, but could be related to notifications, reminders,
hardware, other assessments, etc., eg,

- number of times completed (in a specified time period)
- time since last completed
- time since last notification
- time since last started
- completion of prequisite assessments
- minimum/maximum screen dimensions
- required sensors

If we generalize, we could combine different types of constraints without much/any additional coding, maybe prerequisite assessments completed with some minimum recency.

**Comment by shnizzedy** [comment]
> also regarding constraints do take a look at SHACL (my world of linked things).

:+1:

**Comment by satra** [comment]
@shnizzedy - i like the idea of combining those things. perhaps this is one way of specifying it:

1. constraints (cannot be ignored by an implementer - if these are not satisfied then the particular implementation should raise an error if such an activity/activity-set is being exercised)
- hardware (mic required, accelerometer required, specific devices, etc.,.)
- timing and branching logic
- ui

2. hints (can be ignored by an implementer, but would be great if they supported this)
- ui: what kind of widget to use
- timing

**Comment by ccraddock** [comment]
Here are a few of the things that we would need for scheduling, I apologize for any duplication with the previous posts. 

Issues that we have had with the Beiwe system are:
- it only allows you to schedule by the day of the week, 
- surveys hang around until they are completed
- there is a good deal of variance in the time of day when surveys appear 
- poor logging of the survey presentation times

For scheduling, my users would like:
- to be able to schedule by day of the week, by specific date, or by a non-week based period between surveys. E.g. a survey every other day, or every 10 days
- to have surveys disappear after an allocated amount time
- to have surveys appear at exactly the proscribed time
- to keep full logs on when the survey was intended to be shown, when it was actually shown, and when it was answered
- to be able to send individualized surveys to individual study participants
- to be able to specify a number of surveys to be randomly presented over a period of time. e.g. 3 surveys randomly appearing over the next 10 days

We are also interested in something very similar to Satra's push a button and trigger an assessment approach. But would like to extend this beyond app-based buttons to other buttons or sensors. For example we are deploying in-home environmental monitors and we would like to be able to trigger assessments based on environmental events such as the smoke detector going off, or the home becoming excessively warm. 

We also have a need for the 'always available' types of survey that Satra mentioned, although it would be nice if we could limit the number of times that they can be completed in a day, or perhaps the amount of time that must pass between responses.

I see now that some of these things go beyond survey scheduling, but they may have some impact. 

I will look closely at the cron interface, but if it can easily handle everything on our want list, then I am all for it.

**Comment by ccraddock** [comment]
also would be nice to have macros to be able to add the date and time to survey text

E.g.

"This is the survey for {day} and {time}, you will have {timeout} minutes to complete it before it disappears".

**Comment by satra** [comment]
@ccraddock - that's a great idea. i think this could go into the UI hints section. something like mindlogger would use it, but some other tool may not. we may need to work out some details, but i can see that we may consider a header/footer section description in the UI, where things like this goes.

**Comment by satra** [comment]
@ccraddock - did you look into the cron format? are there use cases you have that cron does not handle (besides randomization, time limit/duration)

**Comment by satra** [comment]
superceded by #172
