### ISSUE TITLE
Add pages for LORIS compatibility

### ISSUE THREAD

**Issue by akeshavan** [ReproNim/reproschema#85]
example, in PHQ-9 activity, under the "ui" key:

```        
"pages": {
            "page1": [
                "phq9_1",
                "phq9_2
            ],
            "page2":  [
                "phq9_3",
                "phq9_4
            ]
        },
```

**Comment by akeshavan** [comment]
@zaliqarosli

**Comment by zaliqarosli** [comment]
@akeshavan hey anisha, where (in which files?) should I be making these changes for these upcoming PRs?

**Comment by shnizzedy** [comment]
Like in [#88](https://github.com/ReproNim/schema-standardization/issues/88#issuecomment-478591453),

> I'd vote for middleware for this request, some script that compiles a file at whatever level of depth LORIS wants.

Does LORIS want a max of 2 questions per page, like in [the example above](https://github.com/ReproNim/schema-standardization/issues/85#issue-427020154), or how do we determine where to paginate?

**Comment by akeshavan** [comment]
Pagination can be a key added at the "activity" level. @zaliqarosli if you want to make a copy of the PHQ-9 folder (call it PHQ-9-LORIS or something), add a "pages" key in the "ui" object of the activity schema: (e.g. https://github.com/ReproNim/schema-standardization/blob/master/activities/PHQ-9/phq9_schema.jsonld) and also add it to the context (https://github.com/ReproNim/schema-standardization/blob/master/contexts/generic.jsonld)

**Comment by akeshavan** [comment]
@shnizzedy in LORIS, the researcher is able to choose which items go on which pages. Its not something we need in Mindlogger, so we won't use it, but it will be there for compatibility with LORIS
