### ISSUE TITLE
LORIS compatibility/ general need

### ISSUE THREAD

**Issue by akeshavan** [ReproNim/reproschema#88]
We need a way to serialize a jsonld into a single file. @satra please guide us!

**Comment by shnizzedy** [comment]
Why?

**Comment by sanuann** [comment]
Even I thought so. Why?

**Comment by akeshavan** [comment]
This is a request from the LORIS team! It would be great to use they same schema — that way LORIS assessments can be in Mindlogger and vice versa.

**Comment by shnizzedy** [comment]
I'd vote for middleware for this request, some script that compiles a file at whatever level of depth LORIS wants.

**Comment by akeshavan** [comment]
Yep!
